config/routes.rb
Rails.application.routes.draw do

  resources :sync, only: [:index]

  resources :users, :deposits

  resources :deposits do
    post :accept, on: :member, as: :accept
    post :reject, on: :member, as: :reject
  end

  root 'deposits#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post], as: :auth # used by omniauth
  match '/signin', to: 'sessions#new', via: [:get, :post]
  match '/signout', to: 'sessions#destroy', via: [:get, :post]

end

app/views/shared/_flash.html.haml
= flash_messages

app/views/shared/_footer.html.haml
%footer(class='library-footer' role='contentinfo')
  .row.footer-info
    %h2(class='sr-only')library website footer information
    %p(class='repository-footer-info')
  .row.lg-copyright-footer
    .col-md-12.copyright-footer(aria-label='university library copyright info')
      %p
        %a(href='http://illinois.edu' aria-label='University of Illinois website link')
          = image_tag('illinois_wordmark_footer.png', alt: 'University of Illinois Logo')
      © 2014 University of Illinois Board of Trustees

app/views/shared/_header.html.haml
.repository-header
  = link_to 'SEAD DSpace Agent', deposits_path

app/views/shared/_header_navbar.html.haml
%div{'data-no-turbolink' => ''}
  / Static navbar
  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{'aria-controls' => 'navbar', 'aria-expanded' => 'false', 'data-target' => '#navbar', 'data-toggle' => 'collapse', :type => 'button'}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => '/'} SEAD IDEALS Deposit Queue
      #navbar.navbar-collapse.collapse
        %ul.nav.navbar-nav.navbar-right
          - if current_user
            %li= link_to 'Log out', signout_path, class: 'btn btn-signout'
          - else
            - if SEAD2_AGENT_CONFIG.has_key?(:local_mode) && SEAD2_AGENT_CONFIG[:local_mode]
              %li.dropdown
                %a.dropdown-toggle{'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', :href => '#', :role => 'button'}
                  Log
                  In
                  %span.caret
                %ul.dropdown-menu.login-form
                  = form_tag '/auth/identity/callback' do
                    %li
                      .form-group
                        = label_tag :auth_key, 'Email', :class => 'control-label'
                        %br/
                        = text_field_tag :auth_key
                    %li
                      .form-group
                        = label_tag :password, 'Password', :class => 'control-label'
                        %br/
                        = password_field_tag :password
                    %li
                      .actions
                        = submit_tag 'Sign In'
                        %br/
                        = link_to 'Create Account', '/auth/identity/register'
            - else
              %li= link_to 'Log in with NetID', signin_path, class: 'btn btn-signin'
    / /.nav-collapse

app/views/shared/_library_header.html.haml
%body
  %header.library-header.img-responsive
    %h1.sr-only University Library, University of Illinois at Urbana-Champaign
    .container-fluid
      = link_to 'http://www.library.illinois.edu', target: '_blank' do
        = image_tag("library_wordmark_horizontal.png", class: "img-responsive banner-image-library")