config/routes.rb
Rails.application.routes.draw do

  resources :sync, only: [:index]

  resources :users, :deposits

  resources :deposits do
    post :accept, on: :member, as: :accept
    post :reject, on: :member, as: :reject
  end

  root 'deposits#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post], as: :auth # used by omniauth
  match '/signin', to: 'sessions#new', via: [:get, :post]
  match '/signout', to: 'sessions#destroy', via: [:get, :post]

end

app/models/deposit.rb
class Deposit < ActiveRecord::Base
  has_many :statuses, dependent: :destroy
  has_many :research_objects, dependent: :destroy

  serialize :creator
  serialize :abstract

  attr_reader :deposit_license_accepted

  def deposit_license_accepted=(string_value)
    @deposit_license_accepted = (string_value == '1')
  end

  def self.sync_from_api
    SeadApi.sync_deposits
  end

end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  before_action :set_deposit, only: [:show, :edit, :update, :destroy]

  # GET /deposits
  # GET /deposits.json
  def index
    @deposits = Deposit.all
  end

  # GET /deposits/1
  # GET /deposits/1.json
  def show
    @deposit = Deposit.find( params[:id] )
    @research_object = @deposit.research_objects.first # TODO: make sure there will only be one of these!!!
    @aggregated_resources = @research_object.aggregated_resources
    t = true
  end

  # GET /deposits/new
  def new
    @deposit = Deposit.new
  end

  # POST /deposits
  # POST /deposits.json
  def create
    @deposit = Deposit.new(deposit_params)

    respond_to do |format|
      if @deposit.save
        format.html { redirect_to @deposit, notice: 'Deposit was successfully created.' }
        format.json { render :show, status: :created, location: @deposit }
      else
        format.html { render :new }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deposits/1
  # PATCH/PUT /deposits/1.json
  def update
    respond_to do |format|
      if @deposit.update(deposit_params)
        format.html { redirect_to @deposit, notice: 'Deposit was successfully updated.' }
        format.json { render :show, status: :ok, location: @deposit }
      else
        format.html { render :edit }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deposits/1
  # DELETE /deposits/1.json
  def destroy
    @deposit.destroy
    respond_to do |format|
      format.html { redirect_to deposits_url, notice: 'Deposit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /deposits/1/accept
  def accept
    @deposit = Deposit.find(params[:id])
    @research_object = @deposit.research_objects.first # TODO: make sure there will only be one of these!!!
    @aggregated_resources = @research_object.aggregated_resources
    # if accept = true then run code to process the ro
    # else run code to reject it
    if @deposit.update(deposit_params)

      if @deposit.deposit_license_accepted

        #TODO: send RO to dspace!

        redirect_to deposits_url, notice: "Deposit #{@deposit.id} accepted!"
      else
        flash['error'] = 'You must grant the IDEALS Distribution License in order to deposit!'
        respond_to do |format|
          format.html { render :show }
          format.json { render json: @deposit.errors, status: :unprocessable_entity }
        end
        render :show
      end

    else
      respond_to do |format|
        format.html { render :show }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  def reject
    @deposit = Deposit.find( params[:id] )
    redirect_to deposits_url, notice: "Deposit #{@deposit.id} rejected!"
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_deposit
    @deposit = Deposit.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def deposit_params
    params.require(:deposit).permit(:deposit_license_accepted)
  end
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/views/deposits/_deposit_form.html.haml
= form_for @deposit, url: accept_deposit_path, method: :post do |f|
  - if @deposit.errors.any?
    #error_explanation
      %h2
        = pluralize(@deposit.errors.count, "error")
        prohibited this deposit from being saved:
      %ul
        - @deposit.errors.full_messages.each do |message|
          %li= message

  %h2.deposit-show IDEALS Distribution License
  .deposit-show-license
    %p
      In order for IDEALS to reproduce, translate and distribute your submission worldwide, your agreement to
      the following terms is necessary. Please take a moment to read the terms of this license. By clicking
      "I Grant the License", you indicate that you grant the following terms of the license. See the IDEALS
      Copyright Policy for more information.
    %p
      If you have any concerns or questions about this license, we suggest that you contact the IDEALS Staff
      to resolve them.
    .container.well{style: 'overflow-y: scroll; height: 24em;'}
      %h3 IDEALS Deposit Agreement: Non-Exclusive Distribution and Preservation License
      %p
        To properly administer the Illinois Digital Environment for Access to Learning and Scholarship (IDEALS)
        and preserve the contents for future use, the Board of Trustees of the University of Illinois on behalf
        of its Urbana-Champaign campus (the "University") requires certain permissions and warrants from you,
        the author(s) and/or copyright owner. If you are the copyright owner, by accepting this license, you
        still retain copyright to your work and do not give up the right to submit the work to publishers or
        other repositories. If you are not the copyright owner, you represent that the copyright owner has given
        you permission to deposit the work.
      %p
        %strong
          By accepting (clicking through) this license, you grant to the University the non-exclusive right to
          reproduce, translate (as described below), and distribute the submission, including the descriptive
          information (metadata) and abstract, in any format or medium worldwide and royalty-free, including, but
          not limited to, publication over the Internet, except as provided for by an addendum to this agreement.
      %p
        When provided, the University will clearly identify your name(s) as the author(s) or copyright owner(s) of
        the submission as well as the name(s) of the copyright owner(s) if different from your name(s), include a
        statement of your copyright, and will not make any alteration, other than as allowed by this license, to
        your submission.
      %p
        You agree that the University may translate the submission to any medium or format for the purposes of
        security, back-up, and preservation. You agree that the University may make multiple copies of the
        submission for the purposes of security, back-up, and preservation.
      %p
        %strong
          If you cannot make all of the following representations, then you shall contact the IDEALS Staff at
          %a{:href => 'mailto:ideals-gen@illinois.edu'} ideals-gen@illinois.edu
          before proceeding further. In order to make this submission, you represent that:
      %ol
        %li
          You have the right to grant the rights contained in the license.
        %li
          This submission does not, to the best of your knowledge, infringe on anyone's copyright or other
          intellectual property rights.
        %li
          If the submission does contain material for which you do not hold copyright and that exceeds fair use,
          you have obtained the unrestricted permission of the copyright owner to grant the University the rights
          required by this license and that such third-party owned material is clearly identified and acknowledged
          within the text or content of the submission.
        %li
          The submission does not contain any confidential information, proprietary information of others or
          export controlled information.
        %li
          There are not any restrictions or required publication delays on the distribution of the submission by
          the University.
        %li
          The information you provide about the submission is accurate.
      %p
        %strong
          You understand that if copyright terms for, or ownership of, the submission change, it is your
          responsibility to notify the University of these changes.
      %p
        %strong
          You understand that you may request that the submission be withdrawn from IDEALS, and, in such an event,
          the descriptive information (metadata) will be retained and a copy of the submission will be retained in
          a 'dark archive' where it is no longer publicly accessible. The exception to this is requests to withdraw
          theses and dissertations electronically deposited with the Graduate College; in those cases, you
          understand that you must contact the Graduate College at
          %a{:href => 'mailto:thesis@illinois.edu'} thesis@illinois.edu
          to make such a request.
      %p
        If the submission is based upon work that has been sponsored or supported by an agency or organization
        other than the University, you must fulfill any right of review or other obligations required by the
        contract or agreement with such an agency or organization before depositing into IDEALS.
      %p
        By accepting this license, you acknowledge that you have read and agreed to the terms of this agreement
        and all related IDEALS and University policies.
    %p
      Distribution license:
    %p
      = f.label :deposit_license_accepted do
        = f.check_box :deposit_license_accepted, required: true
        I Grant the License

  -#.field
  -#  = f.label :email
  -#  %br/
  -#  = f.text_field :email

  %h2.deposit-show Actions
  %p.actions
    = f.submit 'Deposit into IDEALS', class: 'btn btn-success', data: {confirm: 'Are you sure?'}
    = link_to 'Reject Deposit', reject_deposit_path, method: :post, class: 'btn btn-danger', data: {confirm: 'Are you sure?'}
    %span.pull-right
      = link_to 'Cancel', deposits_path, class: 'btn btn-default'

app/views/deposits/_form.html.haml
= form_for(@deposit) do |f|
  - if @deposit.errors.any?
    #error_explanation
      %h2
        = pluralize(@deposit.errors.count, "error")
        prohibited this deposit from being saved:
      %ul
        - @deposit.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :author
    %br/
    = f.text_field :author
  .field
    = f.label :creation_date
    %br/
    = f.date_select :creation_date
  .field
    = f.label :project_url
    %br/
    = f.text_field :project_url
  .field
    = f.label :status
    %br/
    = f.text_field :status
  .field
    = f.label :state
    %br/
    = f.text_field :state
  .actions
    = f.submit

app/views/deposits/_ideals_license_modal.html.haml
/ Modal
#UIUCLicenseModal.modal.fade{'aria-hidden' => 'true', 'aria-labelledby' => 'UIUCLicenseModal', :role => 'dialog', :style => 'display: none;', :tabindex => '-1'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{'aria-label' => 'Close', 'data-dismiss' => 'modal', :type => 'button'}
          %span{'aria-hidden' => 'true'} ×
        %h2#myModalLabel.modal-title IDEALS Distribution License
      .modal-body
        %p
          In order for IDEALS to reproduce, translate and distribute your submission worldwide, your agreement to
          the following terms is necessary. Please take a moment to read the terms of this license. By clicking
          "I Grant the License", you indicate that you grant the following terms of the license. See the IDEALS
          Copyright Policy for more information.
        %p
          If you have any concerns or questions about this license, we suggest that you contact the IDEALS Staff
          to resolve them.
        .well{style: 'overflow-y: scroll; height: 15em;'}
          %h3 IDEALS Deposit Agreement: Non-Exclusive Distribution and Preservation License
          %p
            To properly administer the Illinois Digital Environment for Access to Learning and Scholarship (IDEALS)
            and preserve the contents for future use, the Board of Trustees of the University of Illinois on behalf
            of its Urbana-Champaign campus (the "University") requires certain permissions and warrants from you,
            the author(s) and/or copyright owner. If you are the copyright owner, by accepting this license, you
            still retain copyright to your work and do not give up the right to submit the work to publishers or
            other repositories. If you are not the copyright owner, you represent that the copyright owner has given
            you permission to deposit the work.
          %p
            %strong
              By accepting (clicking through) this license, you grant to the University the non-exclusive right to
              reproduce, translate (as described below), and distribute the submission, including the descriptive
              information (metadata) and abstract, in any format or medium worldwide and royalty-free, including, but
              not limited to, publication over the Internet, except as provided for by an addendum to this agreement.
          %p
            When provided, the University will clearly identify your name(s) as the author(s) or copyright owner(s) of
            the submission as well as the name(s) of the copyright owner(s) if different from your name(s), include a
            statement of your copyright, and will not make any alteration, other than as allowed by this license, to
            your submission.
          %p
            You agree that the University may translate the submission to any medium or format for the purposes of
            security, back-up, and preservation. You agree that the University may make multiple copies of the
            submission for the purposes of security, back-up, and preservation.
          %p
            %strong
              If you cannot make all of the following representations, then you shall contact the IDEALS Staff at
              %a{:href => 'mailto:ideals-gen@illinois.edu'} ideals-gen@illinois.edu
              before proceeding further. In order to make this submission, you represent that:
          %ol
            %li
              You have the right to grant the rights contained in the license.
            %li
              This submission does not, to the best of your knowledge, infringe on anyone's copyright or other
              intellectual property rights.
            %li
              If the submission does contain material for which you do not hold copyright and that exceeds fair use,
              you have obtained the unrestricted permission of the copyright owner to grant the University the rights
              required by this license and that such third-party owned material is clearly identified and acknowledged
              within the text or content of the submission.
            %li
              The submission does not contain any confidential information, proprietary information of others or
              export controlled information.
            %li
              There are not any restrictions or required publication delays on the distribution of the submission by
              the University.
            %li
              The information you provide about the submission is accurate.
          %p
            %strong
              You understand that if copyright terms for, or ownership of, the submission change, it is your
              responsibility to notify the University of these changes.
          %p
            %strong
              You understand that you may request that the submission be withdrawn from IDEALS, and, in such an event,
              the descriptive information (metadata) will be retained and a copy of the submission will be retained in
              a 'dark archive' where it is no longer publicly accessible. The exception to this is requests to withdraw
              theses and dissertations electronically deposited with the Graduate College; in those cases, you
              understand that you must contact the Graduate College at
              %a{:href => 'mailto:thesis@illinois.edu'} thesis@illinois.edu
              to make such a request.
          %p
            If the submission is based upon work that has been sponsored or supported by an agency or organization
            other than the University, you must fulfill any right of review or other obligations required by the
            contract or agreement with such an agency or organization before depositing into IDEALS.
          %p
            By accepting this license, you acknowledge that you have read and agreed to the terms of this agreement
            and all related IDEALS and University policies.
        %p
          Distribution license:
        = label_tag do
          = check_box_tag 'licenseAgreement', required: true
          I Grant the License
      .modal-footer
        %button.btn.btn-default{'data-dismiss' => 'modal', :type => 'button'} Close

app/views/deposits/edit.html.haml
%h1 Editing Deposit
= render 'form'
= link_to 'Show', @deposit
|
= link_to 'Back', deposits_path

app/views/deposits/index.html.haml
%h1 Deposits
%p
  = link_to 'Sync Deposits', '/sync', class: 'btn btn-warning'

.row
  .col-sm-12
    %h2 Deposits Awaiting Approval
    %ul.deposit-list
      - @deposits.each do |deposit|
        %li.deposit-item
          .deposit-description
            .deposit-title
              = link_to deposit.title, deposit
            .deposit-info
              %span.author
                = deposit.creator.map{|str| str}.join(', ')
              %span.publisher-date
                %span.date
                  = "(#{deposit.created.strftime('%F')})"
            .deposit-abstract
              = deposit.abstract[0]

app/views/deposits/new.html.haml
%h1 New Deposit
= render 'form'
= link_to 'Back', deposits_path

app/views/deposits/show.html.haml
%h1= @deposit[:title]
.deposit-show-authors
  = @deposit[:creator].map{|str| str}.join(', ')

%h2.deposit-show Identifiers
.deposit-show-adminmd
  %table.table.table-striped
    %tbody
      %tr
        %td.field-label Identifier:
        %td= @deposit[:identifier]
      %tr
        %td.field-label Rights Holder:
        %td= link_to @deposit[:rights_holder], @deposit[:rights_holder]
      %tr
        %td.field-label Publication Callback:
        %td= link_to @deposit[:publication_callback], @deposit[:publication_callback]

%h2.deposit-show Files in this item
.deposit-show-files
  %table.table
    %thead
      %tr
        %th File
        %th Description
        %th Format
    %tbody
      - @aggregated_resources.each do |aggregated_resource|
        %tr
          %td= link_to aggregated_resource.title, aggregated_resource.is_version_of
          %td= aggregated_resource.label
          %td= aggregated_resource.mime_type

%h2.deposit-show Description
.deposit-show-metadata
  %table.table.table-striped
    %tbody
      %tr
        %td.field-label Title:
        %td= @research_object.title
      %tr
        %td.field-label Creator(s):
        %td= @research_object.creator.map{|str| str}.join(', ')
      %tr
        %td.field-label Subject(s):
        %td
          - @research_object.topic.each do |topic|
            = topic
            %br
      %tr
        %td.field-label Abstract:
        %td= @research_object.abstract[0]
      %tr
        %td.field-label ORE ReM:
        %td= link_to @research_object.ore_url, @research_object.ore_url

= render partial: 'deposit_form'